#!/usr/bin/env bash

set -e

script/bootstrap

# Install test requirements
pip install --quiet --requirement test-requirements.txt

# Run linting
python -m pylint -f parseable textpipe | tee pylint.out

# Download languages needed for testing
python -m spacy download nl > /dev/null
python -m spacy download en > /dev/null

# Run test with pytest, including doctests
python -m pytest --doctest-modules --junit-xml=pytest.xml

# Run unit tests again, but with nose for coverage report
python -m nose --with-doctest --with-xcoverage --with-xunit --cover-package=textpipe --cover-erase 2> /dev/null
